FROM golang:1.22-alpine AS firstStage
WORKDIR /HyperHive/
COPY ./ ./
RUN go mod download
RUN apk --no-cache add ca-certificates
RUN go build -o ./cmd/binary ./cmd/main.go

FROM scratch
COPY --from=firstStage /HyperHive/cmd/binary /
COPY --from=firstStage /HyperHive/dev.env /
COPY --from=firstStage /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
EXPOSE 8000
CMD [ "/binary" ]
