FROM golang:1.22-alpine AS FirstBuild
COPY ./ /friend
WORKDIR /friend
RUN go mod download
RUN go build -o cmd/build cmd/main.go

FROM scratch
COPY --from=FirstBuild /friend/cmd/build /
COPY --from=FirstBuild /friend/dev.env /
EXPOSE 8002
CMD [ "/build" ]