FROM golang:1.22-alpine AS FirstBuild
COPY ./ /server_service
WORKDIR /server_service
RUN go mod download
RUN go build -o cmd/build cmd/main.go

FROM scratch
COPY --from=FirstBuild /server_service/cmd/build /
COPY --from=FirstBuild /server_service/dev.env /
EXPOSE 8003
CMD ["/build"]
