FROM golang:1.22-alpine AS FirstBuild
WORKDIR /auth-service/
COPY ./ ./
RUN go mod download
RUN go build -o ./cmd/build ./cmd/main.go
RUN apk add -U --no-cache ca-certificates

FROM scratch
COPY --from=FirstBuild /auth-service/cmd/build /
COPY --from=FirstBuild /auth-service/template/ /template/
COPY --from=FirstBuild /auth-service/dev.env /
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
EXPOSE 8081
CMD [ "/build" ]
