// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/pb/friend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	FriendID string `protobuf:"bytes,2,opt,name=FriendID,proto3" json:"FriendID,omitempty"`
}

func (x *FriendRequestRequest) Reset() {
	*x = FriendRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestRequest) ProtoMessage() {}

func (x *FriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestRequest.ProtoReflect.Descriptor instead.
func (*FriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequestRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FriendRequestRequest) GetFriendID() string {
	if x != nil {
		return x.FriendID
	}
	return ""
}

type FriendRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendsID string `protobuf:"bytes,1,opt,name=FriendsID,proto3" json:"FriendsID,omitempty"`
	UserID    string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Status    string `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	UpdateAt  string `protobuf:"bytes,5,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
}

func (x *FriendRequestResponse) Reset() {
	*x = FriendRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestResponse) ProtoMessage() {}

func (x *FriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestResponse.ProtoReflect.Descriptor instead.
func (*FriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{1}
}

func (x *FriendRequestResponse) GetFriendsID() string {
	if x != nil {
		return x.FriendsID
	}
	return ""
}

func (x *FriendRequestResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FriendRequestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FriendRequestResponse) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

type GetPendingListRequestModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OffSet string `protobuf:"bytes,2,opt,name=OffSet,proto3" json:"OffSet,omitempty"`
	Limit  string `protobuf:"bytes,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *GetPendingListRequestModel) Reset() {
	*x = GetPendingListRequestModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPendingListRequestModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingListRequestModel) ProtoMessage() {}

func (x *GetPendingListRequestModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingListRequestModel.ProtoReflect.Descriptor instead.
func (*GetPendingListRequestModel) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{2}
}

func (x *GetPendingListRequestModel) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetPendingListRequestModel) GetOffSet() string {
	if x != nil {
		return x.OffSet
	}
	return ""
}

func (x *GetPendingListRequestModel) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type GetPendingListResponseModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendID        string `protobuf:"bytes,1,opt,name=FriendID,proto3" json:"FriendID,omitempty"`
	UpdateAt        string `protobuf:"bytes,2,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
	UniqueFriendsID string `protobuf:"bytes,3,opt,name=UniqueFriendsID,proto3" json:"UniqueFriendsID,omitempty"`
	UserID          string `protobuf:"bytes,5,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName        string `protobuf:"bytes,6,opt,name=userName,proto3" json:"userName,omitempty"`
	Name            string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePhoto    string `protobuf:"bytes,8,opt,name=profilePhoto,proto3" json:"profilePhoto,omitempty"`
}

func (x *GetPendingListResponseModel) Reset() {
	*x = GetPendingListResponseModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPendingListResponseModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingListResponseModel) ProtoMessage() {}

func (x *GetPendingListResponseModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingListResponseModel.ProtoReflect.Descriptor instead.
func (*GetPendingListResponseModel) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{3}
}

func (x *GetPendingListResponseModel) GetFriendID() string {
	if x != nil {
		return x.FriendID
	}
	return ""
}

func (x *GetPendingListResponseModel) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

func (x *GetPendingListResponseModel) GetUniqueFriendsID() string {
	if x != nil {
		return x.UniqueFriendsID
	}
	return ""
}

func (x *GetPendingListResponseModel) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetPendingListResponseModel) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetPendingListResponseModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPendingListResponseModel) GetProfilePhoto() string {
	if x != nil {
		return x.ProfilePhoto
	}
	return ""
}

type FriendListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friend *GetPendingListRequestModel `protobuf:"bytes,1,opt,name=Friend,proto3" json:"Friend,omitempty"`
}

func (x *FriendListRequest) Reset() {
	*x = FriendListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListRequest) ProtoMessage() {}

func (x *FriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListRequest.ProtoReflect.Descriptor instead.
func (*FriendListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{4}
}

func (x *FriendListRequest) GetFriend() *GetPendingListRequestModel {
	if x != nil {
		return x.Friend
	}
	return nil
}

type FriendListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends []*GetPendingListResponseModel `protobuf:"bytes,1,rep,name=Friends,proto3" json:"Friends,omitempty"`
}

func (x *FriendListResponse) Reset() {
	*x = FriendListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListResponse) ProtoMessage() {}

func (x *FriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListResponse.ProtoReflect.Descriptor instead.
func (*FriendListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{5}
}

func (x *FriendListResponse) GetFriends() []*GetPendingListResponseModel {
	if x != nil {
		return x.Friends
	}
	return nil
}

type GetReceivedFriendRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Received *GetPendingListRequestModel `protobuf:"bytes,1,opt,name=Received,proto3" json:"Received,omitempty"`
}

func (x *GetReceivedFriendRequestRequest) Reset() {
	*x = GetReceivedFriendRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceivedFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceivedFriendRequestRequest) ProtoMessage() {}

func (x *GetReceivedFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceivedFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*GetReceivedFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{6}
}

func (x *GetReceivedFriendRequestRequest) GetReceived() *GetPendingListRequestModel {
	if x != nil {
		return x.Received
	}
	return nil
}

type GetReceivedFriendRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Received []*GetPendingListResponseModel `protobuf:"bytes,1,rep,name=Received,proto3" json:"Received,omitempty"`
}

func (x *GetReceivedFriendRequestResponse) Reset() {
	*x = GetReceivedFriendRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceivedFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceivedFriendRequestResponse) ProtoMessage() {}

func (x *GetReceivedFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceivedFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*GetReceivedFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{7}
}

func (x *GetReceivedFriendRequestResponse) GetReceived() []*GetPendingListResponseModel {
	if x != nil {
		return x.Received
	}
	return nil
}

type GetSendFriendRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Send *GetPendingListRequestModel `protobuf:"bytes,1,opt,name=Send,proto3" json:"Send,omitempty"`
}

func (x *GetSendFriendRequestRequest) Reset() {
	*x = GetSendFriendRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSendFriendRequestRequest) ProtoMessage() {}

func (x *GetSendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*GetSendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{8}
}

func (x *GetSendFriendRequestRequest) GetSend() *GetPendingListRequestModel {
	if x != nil {
		return x.Send
	}
	return nil
}

type GetSendFriendRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Send []*GetPendingListResponseModel `protobuf:"bytes,1,rep,name=Send,proto3" json:"Send,omitempty"`
}

func (x *GetSendFriendRequestResponse) Reset() {
	*x = GetSendFriendRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSendFriendRequestResponse) ProtoMessage() {}

func (x *GetSendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*GetSendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{9}
}

func (x *GetSendFriendRequestResponse) GetSend() []*GetPendingListResponseModel {
	if x != nil {
		return x.Send
	}
	return nil
}

type GetBlockFriendRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *GetPendingListRequestModel `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
}

func (x *GetBlockFriendRequestRequest) Reset() {
	*x = GetBlockFriendRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockFriendRequestRequest) ProtoMessage() {}

func (x *GetBlockFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*GetBlockFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlockFriendRequestRequest) GetBlock() *GetPendingListRequestModel {
	if x != nil {
		return x.Block
	}
	return nil
}

type GetBlockFriendRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block []*GetPendingListResponseModel `protobuf:"bytes,1,rep,name=Block,proto3" json:"Block,omitempty"`
}

func (x *GetBlockFriendRequestResponse) Reset() {
	*x = GetBlockFriendRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockFriendRequestResponse) ProtoMessage() {}

func (x *GetBlockFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*GetBlockFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlockFriendRequestResponse) GetBlock() []*GetPendingListResponseModel {
	if x != nil {
		return x.Block
	}
	return nil
}

type UpdateFriendshipStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendShipID string `protobuf:"bytes,1,opt,name=FriendShipID,proto3" json:"FriendShipID,omitempty"`
	Status       string `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *UpdateFriendshipStatusRequest) Reset() {
	*x = UpdateFriendshipStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_friend_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFriendshipStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendshipStatusRequest) ProtoMessage() {}

func (x *UpdateFriendshipStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_friend_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendshipStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateFriendshipStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_friend_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateFriendshipStatusRequest) GetFriendShipID() string {
	if x != nil {
		return x.FriendShipID
	}
	return ""
}

func (x *UpdateFriendshipStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pkg_pb_friend_proto protoreflect.FileDescriptor

var file_pkg_pb_friend_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x14, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x44, 0x22, 0x81,
	0x01, 0x0a, 0x15, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x73, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x22, 0x62, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x53,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x53, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xeb, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x28,
	0x0a, 0x0f, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x74, 0x6f,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x11, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x06, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x22, 0x4c,
	0x0a, 0x12, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x07, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x22, 0x5a, 0x0a, 0x1f,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x37, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x08,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x22, 0x5c, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x08,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x08, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x22, 0x4e, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6e,
	0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x22, 0x50, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6e,
	0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x22, 0x51, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x53, 0x0a, 0x1d, 0x47,
	0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0x5b, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x68, 0x69, 0x70, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x53,
	0x68, 0x69, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xe8, 0x03,
	0x0a, 0x0d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x40, 0x0a, 0x0d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x35, 0x0a, 0x0a, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x12, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73,
	0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_friend_proto_rawDescOnce sync.Once
	file_pkg_pb_friend_proto_rawDescData = file_pkg_pb_friend_proto_rawDesc
)

func file_pkg_pb_friend_proto_rawDescGZIP() []byte {
	file_pkg_pb_friend_proto_rawDescOnce.Do(func() {
		file_pkg_pb_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_friend_proto_rawDescData)
	})
	return file_pkg_pb_friend_proto_rawDescData
}

var file_pkg_pb_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_pb_friend_proto_goTypes = []interface{}{
	(*FriendRequestRequest)(nil),             // 0: FriendRequestRequest
	(*FriendRequestResponse)(nil),            // 1: FriendRequestResponse
	(*GetPendingListRequestModel)(nil),       // 2: GetPendingListRequestModel
	(*GetPendingListResponseModel)(nil),      // 3: GetPendingListResponseModel
	(*FriendListRequest)(nil),                // 4: FriendListRequest
	(*FriendListResponse)(nil),               // 5: FriendListResponse
	(*GetReceivedFriendRequestRequest)(nil),  // 6: GetReceivedFriendRequestRequest
	(*GetReceivedFriendRequestResponse)(nil), // 7: GetReceivedFriendRequestResponse
	(*GetSendFriendRequestRequest)(nil),      // 8: GetSendFriendRequestRequest
	(*GetSendFriendRequestResponse)(nil),     // 9: GetSendFriendRequestResponse
	(*GetBlockFriendRequestRequest)(nil),     // 10: GetBlockFriendRequestRequest
	(*GetBlockFriendRequestResponse)(nil),    // 11: GetBlockFriendRequestResponse
	(*UpdateFriendshipStatusRequest)(nil),    // 12: UpdateFriendshipStatusRequest
	(*emptypb.Empty)(nil),                    // 13: google.protobuf.Empty
}
var file_pkg_pb_friend_proto_depIdxs = []int32{
	2,  // 0: FriendListRequest.Friend:type_name -> GetPendingListRequestModel
	3,  // 1: FriendListResponse.Friends:type_name -> GetPendingListResponseModel
	2,  // 2: GetReceivedFriendRequestRequest.Received:type_name -> GetPendingListRequestModel
	3,  // 3: GetReceivedFriendRequestResponse.Received:type_name -> GetPendingListResponseModel
	2,  // 4: GetSendFriendRequestRequest.Send:type_name -> GetPendingListRequestModel
	3,  // 5: GetSendFriendRequestResponse.Send:type_name -> GetPendingListResponseModel
	2,  // 6: GetBlockFriendRequestRequest.Block:type_name -> GetPendingListRequestModel
	3,  // 7: GetBlockFriendRequestResponse.Block:type_name -> GetPendingListResponseModel
	0,  // 8: FriendService.FriendRequest:input_type -> FriendRequestRequest
	4,  // 9: FriendService.FriendList:input_type -> FriendListRequest
	6,  // 10: FriendService.GetReceivedFriendRequest:input_type -> GetReceivedFriendRequestRequest
	8,  // 11: FriendService.GetSendFriendRequest:input_type -> GetSendFriendRequestRequest
	10, // 12: FriendService.GetBlockFriendRequest:input_type -> GetBlockFriendRequestRequest
	12, // 13: FriendService.UpdateFriendshipStatus:input_type -> UpdateFriendshipStatusRequest
	1,  // 14: FriendService.FriendRequest:output_type -> FriendRequestResponse
	5,  // 15: FriendService.FriendList:output_type -> FriendListResponse
	7,  // 16: FriendService.GetReceivedFriendRequest:output_type -> GetReceivedFriendRequestResponse
	9,  // 17: FriendService.GetSendFriendRequest:output_type -> GetSendFriendRequestResponse
	11, // 18: FriendService.GetBlockFriendRequest:output_type -> GetBlockFriendRequestResponse
	13, // 19: FriendService.UpdateFriendshipStatus:output_type -> google.protobuf.Empty
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_pb_friend_proto_init() }
func file_pkg_pb_friend_proto_init() {
	if File_pkg_pb_friend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_friend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPendingListRequestModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPendingListResponseModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceivedFriendRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceivedFriendRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSendFriendRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSendFriendRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockFriendRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockFriendRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_friend_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFriendshipStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_friend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_friend_proto_goTypes,
		DependencyIndexes: file_pkg_pb_friend_proto_depIdxs,
		MessageInfos:      file_pkg_pb_friend_proto_msgTypes,
	}.Build()
	File_pkg_pb_friend_proto = out.File
	file_pkg_pb_friend_proto_rawDesc = nil
	file_pkg_pb_friend_proto_goTypes = nil
	file_pkg_pb_friend_proto_depIdxs = nil
}
